<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.51" os="Windows 7" host="LH7U05CG5443KYD"><DocLocation><![CDATA[C:\Proj_WebStrat_UFT_Automation\Drivers\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res13]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="0" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/15/2018 - 11:10:12]]></Time>
<TimeTick>1515994812</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[1/15/2018 - 11:10:12]]></Time>
<TimeTick>1515994812</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "[ WebEdit ]" object's parent "[ Browser ]" (class Browser).
Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[1/15/2018 - 11:10:35]]></Time>
<TimeTick>1515994835</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = Web.Strat Login<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[1/15/2018 - 11:10:35]]></Time>
<TimeTick>1515994835</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="21" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="20" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ WebEdit ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;[ WebEdit ]&quot; object's parent &quot;[ Browser ]&quot; (class Browser).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStratUser.vbs<BR/>Line (15): &quot;Browser(&quot;name:=Web.Strat Login&quot;).Page(&quot;title:=Web.Strat Login&quot;).WebEdit(&quot;name:=TextBoxUserId&quot;,&quot;html tag:=INPUT&quot;,&quot;type:=text&quot;).Set &quot;ERC_WSD&quot;&quot;.]]></Details>
<Time><![CDATA[1/15/2018 - 11:10:35]]></Time>
<TimeTick>1515994835</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="22" status="Failed" Source="C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStratUser.vbs" SourceLine="14" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPassword ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hss_PATDB"]]></Details>
<Time><![CDATA[1/15/2018 - 11:10:40]]></Time>
<TimeTick>1515994840</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" Source="C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStratUser.vbs" SourceLine="-1" >
<Disp><![CDATA[[ TextBoxPassword ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Login ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/15/2018 - 11:10:40]]></Time>
<TimeTick>1515994840</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" Source="C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStratUser.vbs" SourceLine="-1" >
<Disp><![CDATA[[ Login ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Web.Strat Login ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[1/15/2018 - 11:10:43]]></Time>
<TimeTick>1515994843</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" Source="C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStratUser.vbs" SourceLine="-1" >
<Disp><![CDATA[[ Web.Strat Login ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ WbfTabStrip ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "[ WbfTabStrip ]" object's parent "[ Page ]" (class Page).
Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[1/15/2018 - 11:11:06]]></Time>
<TimeTick>1515994866</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Title = Web.Strat<br>Mercury Class = Page<br>]]></Details>
<Time><![CDATA[1/15/2018 - 11:11:06]]></Time>
<TimeTick>1515994866</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="38" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ WbfTabStrip ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;[ WbfTabStrip ]&quot; object's parent &quot;[ Page ]&quot; (class Page).<BR/>Verify that parent properties match an object currently displayed in your application.<BR/>Function file: C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStratUser.vbs<BR/>Line (46): &quot;Browser(&quot;opentitle:=Web.Strat Login&quot;).page(&quot;title:=Web.Strat&quot;).WbfTabStrip(&quot;html id:=TabStrip1&quot;).Select &quot;Search&quot;&quot;.]]></Details>
<Time><![CDATA[1/15/2018 - 11:11:06]]></Time>
<TimeTick>1515994866</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" status="Failed" Source="C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStratUser.vbs" SourceLine="45" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ WbfTabStrip ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "[ WbfTabStrip ]" object's parent "[ Page ]" (class Page).
Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[1/15/2018 - 11:11:23]]></Time>
<TimeTick>1515994883</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Title = Web.Strat<br>Mercury Class = Page<br>]]></Details>
<Time><![CDATA[1/15/2018 - 11:11:23]]></Time>
<TimeTick>1515994883</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="46" status="Warning" nType="Parent description" Source="C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStratUser.vbs" SourceLine="-1" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="45" status="Failed" nType="Run Error" Source="C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStratUser.vbs" SourceLine="-1" >
<Disp><![CDATA[[ WbfTabStrip ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[1/15/2018 - 11:11:23]]></Time>
<TimeTick>1515994883</TimeTick>
<NodeArgs eType="General" icon="0" nRep="47" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/15/2018 - 11:09:40" eTime="1/15/2018 - 11:11:23" passed="1" failed="5" warnings="3" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="2" nRep="6" status="Failed" >
<Disp><![CDATA[Driver Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="1/15/2018 - 11:09:29" eTime="1/15/2018 - 11:11:23" passed="1" failed="5" warnings="3" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>