<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.51" os="Windows 7" host="LH7U05CG5170952"><DocLocation><![CDATA[C:\Proj_WebStrat_UFT_Automation\Drivers\WebStratApplication]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[WebStratApplication]]></DName>
<Res><![CDATA[Res29]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[WebStrat_Automation]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:09]]></Time>
<TimeTick>1523354589</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:09]]></Time>
<TimeTick>1523354589</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ TextBoxUserId ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ERC_WSD"]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:23]]></Time>
<TimeTick>1523354603</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" >
<Disp><![CDATA[[ TextBoxUserId ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPassword ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hss_PATDB"]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:23]]></Time>
<TimeTick>1523354603</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" >
<Disp><![CDATA[[ TextBoxPassword ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Login ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:23]]></Time>
<TimeTick>1523354603</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" >
<Disp><![CDATA[[ Login ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:30]]></Time>
<TimeTick>1523354610</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:30]]></Time>
<TimeTick>1523354610</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:31]]></Time>
<TimeTick>1523354611</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="29" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Dummy"]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:31]]></Time>
<TimeTick>1523354611</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:31]]></Time>
<TimeTick>1523354611</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:34]]></Time>
<TimeTick>1523354614</TimeTick>
<NodeArgs eType="General" icon="10" nRep="38" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:34]]></Time>
<TimeTick>1523354614</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="41" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:34]]></Time>
<TimeTick>1523354614</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="44" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:33:34]]></Time>
<TimeTick>1523354614</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="45" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[4/10/2018 - 15:34:00]]></Time>
<TimeTick>1523354640</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="61" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:34:00]]></Time>
<TimeTick>1523354640</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="64" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:34:01]]></Time>
<TimeTick>1523354641</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="67" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[4/10/2018 - 15:34:41]]></Time>
<TimeTick>1523354681</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="70" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:01]]></Time>
<TimeTick>1523354701</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:02]]></Time>
<TimeTick>1523354702</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="76" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:03]]></Time>
<TimeTick>1523354703</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="79" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ASC_Claim_Validation"]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:08]]></Time>
<TimeTick>1523354708</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="82" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:08]]></Time>
<TimeTick>1523354708</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="85" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:10]]></Time>
<TimeTick>1523354710</TimeTick>
<NodeArgs eType="General" icon="10" nRep="88" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:10]]></Time>
<TimeTick>1523354710</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="91" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:11]]></Time>
<TimeTick>1523354711</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="94" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:11]]></Time>
<TimeTick>1523354711</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="95" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:22]]></Time>
<TimeTick>1523354722</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="111" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:23]]></Time>
<TimeTick>1523354723</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="114" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:23]]></Time>
<TimeTick>1523354723</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="117" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:41]]></Time>
<TimeTick>1523354741</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="120" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:41]]></Time>
<TimeTick>1523354741</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="123" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:42]]></Time>
<TimeTick>1523354742</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="126" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:43]]></Time>
<TimeTick>1523354743</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="129" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["apc_paystat_s"]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:48]]></Time>
<TimeTick>1523354748</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="132" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:48]]></Time>
<TimeTick>1523354748</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="135" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:50]]></Time>
<TimeTick>1523354750</TimeTick>
<NodeArgs eType="General" icon="10" nRep="138" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:51]]></Time>
<TimeTick>1523354751</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="141" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:51]]></Time>
<TimeTick>1523354751</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="144" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:35:51]]></Time>
<TimeTick>1523354751</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="145" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[4/10/2018 - 15:36:16]]></Time>
<TimeTick>1523354776</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="161" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:36:16]]></Time>
<TimeTick>1523354776</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="164" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:36:18]]></Time>
<TimeTick>1523354778</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="167" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[4/10/2018 - 15:36:57]]></Time>
<TimeTick>1523354817</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="170" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:18]]></Time>
<TimeTick>1523354838</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="173" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:19]]></Time>
<TimeTick>1523354839</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="176" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:20]]></Time>
<TimeTick>1523354840</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="179" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["EXTFee_AT"]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:25]]></Time>
<TimeTick>1523354845</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="182" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:25]]></Time>
<TimeTick>1523354845</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="185" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:28]]></Time>
<TimeTick>1523354848</TimeTick>
<NodeArgs eType="General" icon="10" nRep="188" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:28]]></Time>
<TimeTick>1523354848</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="191" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:28]]></Time>
<TimeTick>1523354848</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="194" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:28]]></Time>
<TimeTick>1523354848</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="195" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:54]]></Time>
<TimeTick>1523354874</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="211" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:54]]></Time>
<TimeTick>1523354874</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="214" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:37:55]]></Time>
<TimeTick>1523354875</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="217" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[4/10/2018 - 15:38:34]]></Time>
<TimeTick>1523354914</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="220" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:38:54]]></Time>
<TimeTick>1523354934</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="223" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:38:55]]></Time>
<TimeTick>1523354935</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="226" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[4/10/2018 - 15:38:56]]></Time>
<TimeTick>1523354936</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="229" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["WS.V1801.ONMPRF.1.0"]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:01]]></Time>
<TimeTick>1523354941</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="232" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:01]]></Time>
<TimeTick>1523354941</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="235" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:03]]></Time>
<TimeTick>1523354943</TimeTick>
<NodeArgs eType="General" icon="10" nRep="238" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:03]]></Time>
<TimeTick>1523354943</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="241" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:04]]></Time>
<TimeTick>1523354944</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="244" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:04]]></Time>
<TimeTick>1523354944</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="245" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:16]]></Time>
<TimeTick>1523354956</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="261" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:16]]></Time>
<TimeTick>1523354956</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="264" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:17]]></Time>
<TimeTick>1523354957</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="267" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:35]]></Time>
<TimeTick>1523354975</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="270" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:35]]></Time>
<TimeTick>1523354975</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="273" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:36]]></Time>
<TimeTick>1523354976</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="276" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:37]]></Time>
<TimeTick>1523354977</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="279" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["FSUC210_Validation"]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:42]]></Time>
<TimeTick>1523354982</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="282" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/10/2018 - 15:39:42]]></Time>
<TimeTick>1523354982</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="285" >