<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.51" os="Windows 7" host="LH7U05CG5170952"><DocLocation><![CDATA[C:\Proj_WebStrat_UFT_Automation\Drivers\WebStratApplication]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[WebStratApplication]]></DName>
<Res><![CDATA[Res39]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[WebStrat_Automation]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/11/2018 - 10:22:47]]></Time>
<TimeTick>1523422367</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[4/11/2018 - 10:22:47]]></Time>
<TimeTick>1523422367</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ TextBoxUserId ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ERC_WSD"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:07]]></Time>
<TimeTick>1523422387</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" >
<Disp><![CDATA[[ TextBoxUserId ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPassword ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hss_PATDB"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:07]]></Time>
<TimeTick>1523422387</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" >
<Disp><![CDATA[[ TextBoxPassword ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Login ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:07]]></Time>
<TimeTick>1523422387</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" >
<Disp><![CDATA[[ Login ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownPatType ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["02"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:30]]></Time>
<TimeTick>1523422410</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="WebStrat_Automation" SourceLine="83" >
<Disp><![CDATA[[ txtDropDownPatType ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ txtNPI ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:31]]></Time>
<TimeTick>1523422411</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="WebStrat_Automation" SourceLine="88" >
<Disp><![CDATA[[ txtNPI ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ txtTaxonomy ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:32]]></Time>
<TimeTick>1523422412</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" Source="WebStrat_Automation" SourceLine="89" >
<Disp><![CDATA[[ txtTaxonomy ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ DropDownFacilityID ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["010001"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:36]]></Time>
<TimeTick>1523422416</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" Source="WebStrat_Automation" SourceLine="91" >
<Disp><![CDATA[[ DropDownFacilityID ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownPayerID ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["09"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:36]]></Time>
<TimeTick>1523422416</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="36" Source="WebStrat_Automation" SourceLine="93" >
<Disp><![CDATA[[ txtDropDownPayerID ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPtIDMedRec ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["WS.V1804.HOPDP.1.0"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:37]]></Time>
<TimeTick>1523422417</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" Source="WebStrat_Automation" SourceLine="95" >
<Disp><![CDATA[[ TextBoxPtIDMedRec ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ TextBoxAdmitDate ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/1/2018"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:41]]></Time>
<TimeTick>1523422421</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" Source="WebStrat_Automation" SourceLine="97" >
<Disp><![CDATA[[ TextBoxAdmitDate ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ TextBoxDischDate ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/1/2018"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:42]]></Time>
<TimeTick>1523422422</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="45" Source="WebStrat_Automation" SourceLine="98" >
<Disp><![CDATA[[ TextBoxDischDate ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ TextBoxSex ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["M"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:43]]></Time>
<TimeTick>1523422423</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="48" Source="WebStrat_Automation" SourceLine="101" >
<Disp><![CDATA[[ TextBoxSex ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ TextBoxBirth ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["01/01/1977"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:43]]></Time>
<TimeTick>1523422423</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" Source="WebStrat_Automation" SourceLine="103" >
<Disp><![CDATA[[ TextBoxBirth ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownDStat ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["01"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:43]]></Time>
<TimeTick>1523422423</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="54" Source="WebStrat_Automation" SourceLine="105" >
<Disp><![CDATA[[ txtDropDownDStat ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0131"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:43]]></Time>
<TimeTick>1523422423</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="57" Source="WebStrat_Automation" SourceLine="107" >
<Disp><![CDATA[[ WebEdit ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ TextBoxCoder ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18Q2R1"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:44]]></Time>
<TimeTick>1523422424</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="60" Source="WebStrat_Automation" SourceLine="110" >
<Disp><![CDATA[[ TextBoxCoder ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Summary"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:50]]></Time>
<TimeTick>1523422430</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" Source="WebStrat_Automation" SourceLine="116" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:50]]></Time>
<TimeTick>1523422430</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="66" Source="WebStrat_Automation" SourceLine="117" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ dx0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["B699"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:56]]></Time>
<TimeTick>1523422436</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="69" Source="WebStrat_Automation" SourceLine="145" >
<Disp><![CDATA[[ dx0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Onset0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:57]]></Time>
<TimeTick>1523422437</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="72" Source="WebStrat_Automation" SourceLine="146" >
<Disp><![CDATA[[ Onset0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ rev0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0360"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:57]]></Time>
<TimeTick>1523422437</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" Source="WebStrat_Automation" SourceLine="149" >
<Disp><![CDATA[[ rev0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ hcpcs0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0100T"]]></Details>
<Time><![CDATA[4/11/2018 - 10:23:58]]></Time>
<TimeTick>1523422438</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="78" Source="WebStrat_Automation" SourceLine="151" >
<Disp><![CDATA[[ hcpcs0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Units0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:02]]></Time>
<TimeTick>1523422442</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="81" Source="WebStrat_Automation" SourceLine="154" >
<Disp><![CDATA[[ Units0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ date0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/01/2018"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:02]]></Time>
<TimeTick>1523422442</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="84" Source="WebStrat_Automation" SourceLine="156" >
<Disp><![CDATA[[ date0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ charges0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100000"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:03]]></Time>
<TimeTick>1523422443</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="87" Source="WebStrat_Automation" SourceLine="158" >
<Disp><![CDATA[[ charges0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ rev1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0360"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:03]]></Time>
<TimeTick>1523422443</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="90" Source="WebStrat_Automation" SourceLine="161" >
<Disp><![CDATA[[ rev1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ hcpcs1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["C1840"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:04]]></Time>
<TimeTick>1523422444</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="93" Source="WebStrat_Automation" SourceLine="163" >
<Disp><![CDATA[[ hcpcs1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Units1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:06]]></Time>
<TimeTick>1523422446</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="96" Source="WebStrat_Automation" SourceLine="166" >
<Disp><![CDATA[[ Units1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ date1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/01/2018"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:06]]></Time>
<TimeTick>1523422446</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="99" Source="WebStrat_Automation" SourceLine="168" >
<Disp><![CDATA[[ date1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ charges1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100000"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:07]]></Time>
<TimeTick>1523422447</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="102" Source="WebStrat_Automation" SourceLine="170" >
<Disp><![CDATA[[ charges1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Functions ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:10]]></Time>
<TimeTick>1523422450</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="105" Source="WebStrat_Automation" SourceLine="178" >
<Disp><![CDATA[[ Functions ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Web.Strat]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:10]]></Time>
<TimeTick>1523422450</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Web.Strat]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:10]]></Time>
<TimeTick>1523422450</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Group and Price (Ctrl+G).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:10]]></Time>
<TimeTick>1523422450</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="110" Source="WebStrat_Automation" SourceLine="183" >
<Disp><![CDATA[Group and Price (Ctrl+G).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownPatType ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["02"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:27]]></Time>
<TimeTick>1523422467</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="113" Source="WebStrat_Automation" SourceLine="83" >
<Disp><![CDATA[[ txtDropDownPatType ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ txtNPI ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1164403861"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:30]]></Time>
<TimeTick>1523422470</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="116" Source="WebStrat_Automation" SourceLine="88" >
<Disp><![CDATA[[ txtNPI ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ txtTaxonomy ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["282N00000X"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:30]]></Time>
<TimeTick>1523422470</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="119" Source="WebStrat_Automation" SourceLine="89" >
<Disp><![CDATA[[ txtTaxonomy ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ DropDownFacilityID ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["010001"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:34]]></Time>
<TimeTick>1523422474</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="122" Source="WebStrat_Automation" SourceLine="91" >
<Disp><![CDATA[[ DropDownFacilityID ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownPayerID ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["09"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:34]]></Time>
<TimeTick>1523422474</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="125" Source="WebStrat_Automation" SourceLine="93" >
<Disp><![CDATA[[ txtDropDownPayerID ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPtIDMedRec ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["WS.V1804.HOPDP.2.0"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:34]]></Time>
<TimeTick>1523422474</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="128" Source="WebStrat_Automation" SourceLine="95" >
<Disp><![CDATA[[ TextBoxPtIDMedRec ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ TextBoxAdmitDate ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/1/2018"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:35]]></Time>
<TimeTick>1523422475</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="131" Source="WebStrat_Automation" SourceLine="97" >
<Disp><![CDATA[[ TextBoxAdmitDate ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ TextBoxDischDate ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/1/2018"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:35]]></Time>
<TimeTick>1523422475</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="134" Source="WebStrat_Automation" SourceLine="98" >
<Disp><![CDATA[[ TextBoxDischDate ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ TextBoxSex ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["M"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:36]]></Time>
<TimeTick>1523422476</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="137" Source="WebStrat_Automation" SourceLine="101" >
<Disp><![CDATA[[ TextBoxSex ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ TextBoxBirth ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["01/01/1977"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:36]]></Time>
<TimeTick>1523422476</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="140" Source="WebStrat_Automation" SourceLine="103" >
<Disp><![CDATA[[ TextBoxBirth ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownDStat ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["01"]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:37]]></Time>
<TimeTick>1523422477</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="143" Source="WebStrat_Automation" SourceLine="105" >
<Disp><![CDATA[[ txtDropDownDStat ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "[ WebEdit ]" (of class WebEdit).
Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:57]]></Time>
<TimeTick>1523422497</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Type = text<br>Name = WebEdit<br>Mercury Class = WebEdit<br>htmltag = INPUT<br>Html Id = TextBoxBillType<br>Height = 22<br>]]></Details>
<Time><![CDATA[4/11/2018 - 10:24:57]]></Time>
<TimeTick>1523422497</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="161" status="Warning" nType="Description" Source="WebStrat_Automation" SourceLine="107" >
<Disp><![CDATA[[ WebEdit ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="160" status="Failed" nType="Run Error" Source="WebStrat_Automation" SourceLine="107" >
<Disp><![CDATA[[ WebEdit ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ TextBoxCoder ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18Q2R1"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:01]]></Time>
<TimeTick>1523422501</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="164" Source="WebStrat_Automation" SourceLine="110" >
<Disp><![CDATA[[ TextBoxCoder ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Summary"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:07]]></Time>
<TimeTick>1523422507</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="167" Source="WebStrat_Automation" SourceLine="116" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:08]]></Time>
<TimeTick>1523422508</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="170" Source="WebStrat_Automation" SourceLine="117" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object is disabled]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:08]]></Time>
<TimeTick>1523422508</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WbfTabStrip<br>Html Id = TabStrip1<br>]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:08]]></Time>
<TimeTick>1523422508</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="172" status="Warning" nType="Description" Source="WebStrat_Automation" SourceLine="117" >
<Disp><![CDATA[[ TabStrip1 ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="171" status="Failed" nType="Run Error" Source="WebStrat_Automation" SourceLine="117" >
<Disp><![CDATA[[ TabStrip1 ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ dx0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["B699"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:10]]></Time>
<TimeTick>1523422510</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="175" Source="WebStrat_Automation" SourceLine="145" >
<Disp><![CDATA[[ dx0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ Onset0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:11]]></Time>
<TimeTick>1523422511</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="178" Source="WebStrat_Automation" SourceLine="146" >
<Disp><![CDATA[[ Onset0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ rev0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0360"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:11]]></Time>
<TimeTick>1523422511</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="181" Source="WebStrat_Automation" SourceLine="149" >
<Disp><![CDATA[[ rev0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ hcpcs0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0100T"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:11]]></Time>
<TimeTick>1523422511</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="184" Source="WebStrat_Automation" SourceLine="151" >
<Disp><![CDATA[[ hcpcs0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Units0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:13]]></Time>
<TimeTick>1523422513</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="187" Source="WebStrat_Automation" SourceLine="154" >
<Disp><![CDATA[[ Units0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ date0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/01/2018"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:15]]></Time>
<TimeTick>1523422515</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="190" Source="WebStrat_Automation" SourceLine="156" >
<Disp><![CDATA[[ date0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ charges0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100000"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:16]]></Time>
<TimeTick>1523422516</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="193" Source="WebStrat_Automation" SourceLine="158" >
<Disp><![CDATA[[ charges0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ rev1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0360"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:18]]></Time>
<TimeTick>1523422518</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="196" Source="WebStrat_Automation" SourceLine="161" >
<Disp><![CDATA[[ rev1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ hcpcs1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["C1840"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:18]]></Time>
<TimeTick>1523422518</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="199" Source="WebStrat_Automation" SourceLine="163" >
<Disp><![CDATA[[ hcpcs1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ Units1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:20]]></Time>
<TimeTick>1523422520</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="202" Source="WebStrat_Automation" SourceLine="166" >
<Disp><![CDATA[[ Units1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ date1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/01/2018"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:21]]></Time>
<TimeTick>1523422521</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="205" Source="WebStrat_Automation" SourceLine="168" >
<Disp><![CDATA[[ date1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ charges1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100000"]]></Details>
<Time><![CDATA[4/11/2018 - 10:25:21]]></Time>
<TimeTick>1523422521</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="208" Source="WebStrat_Automation" SourceLine="170" >
<Disp><![CDATA[[ charges1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ Functions ].Click]]></Obj>