<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.51" os="Windows 7" host="LH7U05CG5170952"><DocLocation><![CDATA[C:\Proj_WebStrat_UFT_Automation\Drivers\WebStratApplication]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[WebStratApplication]]></DName>
<Res><![CDATA[Res68]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[WebStrat_Automation]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/17/2018 - 16:29:22]]></Time>
<TimeTick>1523962762</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[4/17/2018 - 16:29:22]]></Time>
<TimeTick>1523962762</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ TextBoxUserId ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ERC_WSD"]]></Details>
<Time><![CDATA[4/17/2018 - 16:29:38]]></Time>
<TimeTick>1523962778</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" >
<Disp><![CDATA[[ TextBoxUserId ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPassword ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hss_PATDB"]]></Details>
<Time><![CDATA[4/17/2018 - 16:29:38]]></Time>
<TimeTick>1523962778</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" >
<Disp><![CDATA[[ TextBoxPassword ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Login ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/17/2018 - 16:29:38]]></Time>
<TimeTick>1523962778</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" >
<Disp><![CDATA[[ Login ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownPatType ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["02"]]></Details>
<Time><![CDATA[4/17/2018 - 16:29:48]]></Time>
<TimeTick>1523962788</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="WebStrat_Automation" SourceLine="83" >
<Disp><![CDATA[[ txtDropDownPatType ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ txtNPI ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/17/2018 - 16:29:49]]></Time>
<TimeTick>1523962789</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="WebStrat_Automation" SourceLine="88" >
<Disp><![CDATA[[ txtNPI ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ txtTaxonomy ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/17/2018 - 16:29:49]]></Time>
<TimeTick>1523962789</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" Source="WebStrat_Automation" SourceLine="89" >
<Disp><![CDATA[[ txtTaxonomy ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ DropDownFacilityID ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["111"]]></Details>
<Time><![CDATA[4/17/2018 - 16:29:53]]></Time>
<TimeTick>1523962793</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" Source="WebStrat_Automation" SourceLine="91" >
<Disp><![CDATA[[ DropDownFacilityID ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownPayerID ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04301392"]]></Details>
<Time><![CDATA[4/17/2018 - 16:30:07]]></Time>
<TimeTick>1523962807</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="36" Source="WebStrat_Automation" SourceLine="93" >
<Disp><![CDATA[[ txtDropDownPayerID ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPtIDMedRec ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["WS.AP.18Q2R1.1.0"]]></Details>
<Time><![CDATA[4/17/2018 - 16:30:09]]></Time>
<TimeTick>1523962809</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" Source="WebStrat_Automation" SourceLine="95" >
<Disp><![CDATA[[ TextBoxPtIDMedRec ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ TextBoxAdmitDate ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/1/2018"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:01]]></Time>
<TimeTick>1523962861</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" Source="WebStrat_Automation" SourceLine="97" >
<Disp><![CDATA[[ TextBoxAdmitDate ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ TextBoxDischDate ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/1/2018"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:03]]></Time>
<TimeTick>1523962863</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="46" Source="WebStrat_Automation" SourceLine="98" >
<Disp><![CDATA[[ TextBoxDischDate ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ TextBoxSex ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["M"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:04]]></Time>
<TimeTick>1523962864</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="49" Source="WebStrat_Automation" SourceLine="101" >
<Disp><![CDATA[[ TextBoxSex ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ TextBoxBirth ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["01/01/1977"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:05]]></Time>
<TimeTick>1523962865</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="52" Source="WebStrat_Automation" SourceLine="103" >
<Disp><![CDATA[[ TextBoxBirth ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownDStat ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["01"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:06]]></Time>
<TimeTick>1523962866</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" Source="WebStrat_Automation" SourceLine="105" >
<Disp><![CDATA[[ txtDropDownDStat ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0131"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:07]]></Time>
<TimeTick>1523962867</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="58" Source="WebStrat_Automation" SourceLine="107" >
<Disp><![CDATA[[ WebEdit ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ TextBoxCoder ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18Q2R1"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:07]]></Time>
<TimeTick>1523962867</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="61" Source="WebStrat_Automation" SourceLine="110" >
<Disp><![CDATA[[ TextBoxCoder ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Summary"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:14]]></Time>
<TimeTick>1523962874</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="64" Source="WebStrat_Automation" SourceLine="116" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:16]]></Time>
<TimeTick>1523962876</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="67" Source="WebStrat_Automation" SourceLine="117" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ dx0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["B699"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:55]]></Time>
<TimeTick>1523962915</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="70" Source="WebStrat_Automation" SourceLine="145" >
<Disp><![CDATA[[ dx0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Onset0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:56]]></Time>
<TimeTick>1523962916</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="73" Source="WebStrat_Automation" SourceLine="146" >
<Disp><![CDATA[[ Onset0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ rev0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0100"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:56]]></Time>
<TimeTick>1523962916</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="76" Source="WebStrat_Automation" SourceLine="149" >
<Disp><![CDATA[[ rev0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ hcpcs0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["C9469"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:57]]></Time>
<TimeTick>1523962917</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="79" Source="WebStrat_Automation" SourceLine="151" >
<Disp><![CDATA[[ hcpcs0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Units0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:58]]></Time>
<TimeTick>1523962918</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="82" Source="WebStrat_Automation" SourceLine="154" >
<Disp><![CDATA[[ Units0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ date0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/01/2018"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:59]]></Time>
<TimeTick>1523962919</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="85" Source="WebStrat_Automation" SourceLine="156" >
<Disp><![CDATA[[ date0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ charges0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["500"]]></Details>
<Time><![CDATA[4/17/2018 - 16:31:59]]></Time>
<TimeTick>1523962919</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="88" Source="WebStrat_Automation" SourceLine="158" >
<Disp><![CDATA[[ charges0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ rev1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:00]]></Time>
<TimeTick>1523962920</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="91" Source="WebStrat_Automation" SourceLine="161" >
<Disp><![CDATA[[ rev1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ hcpcs1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["10060"]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:01]]></Time>
<TimeTick>1523962921</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="94" Source="WebStrat_Automation" SourceLine="163" >
<Disp><![CDATA[[ hcpcs1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Units1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:02]]></Time>
<TimeTick>1523962922</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="97" Source="WebStrat_Automation" SourceLine="166" >
<Disp><![CDATA[[ Units1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ date1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/01/2018"]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:03]]></Time>
<TimeTick>1523962923</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="100" Source="WebStrat_Automation" SourceLine="168" >
<Disp><![CDATA[[ date1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ charges1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["500"]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:03]]></Time>
<TimeTick>1523962923</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="103" Source="WebStrat_Automation" SourceLine="170" >
<Disp><![CDATA[[ charges1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Functions ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:06]]></Time>
<TimeTick>1523962926</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="106" Source="WebStrat_Automation" SourceLine="178" >
<Disp><![CDATA[[ Functions ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Web.Strat]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:06]]></Time>
<TimeTick>1523962926</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Web.Strat]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:06]]></Time>
<TimeTick>1523962926</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Group and Price (Ctrl+G).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:06]]></Time>
<TimeTick>1523962926</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="111" Source="WebStrat_Automation" SourceLine="183" >
<Disp><![CDATA[Group and Price (Ctrl+G).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:46]]></Time>
<TimeTick>1523962966</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="126" Source="WebStrat_Automation" SourceLine="240" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:57]]></Time>
<TimeTick>1523962977</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="129" Source="WebStrat_Automation" SourceLine="325" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[New (Alt+N).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/17/2018 - 16:32:57]]></Time>
<TimeTick>1523962977</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="132" Source="WebStrat_Automation" SourceLine="326" >
<Disp><![CDATA[New (Alt+N).Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="110" Source="WebStrat_Automation" SourceLine="183" >
<Disp><![CDATA[Web.Strat]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[VBScript]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:00]]></Time>
<TimeTick>1523962980</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:00]]></Time>
<TimeTick>1523962980</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="136" Source="WebStrat_Automation" SourceLine="329" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownPatType ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["02"]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:42]]></Time>
<TimeTick>1523963022</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="139" Source="WebStrat_Automation" SourceLine="83" >
<Disp><![CDATA[[ txtDropDownPatType ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ txtNPI ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:46]]></Time>
<TimeTick>1523963026</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="142" Source="WebStrat_Automation" SourceLine="88" >
<Disp><![CDATA[[ txtNPI ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ txtTaxonomy ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:47]]></Time>
<TimeTick>1523963027</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="145" Source="WebStrat_Automation" SourceLine="89" >
<Disp><![CDATA[[ txtTaxonomy ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ DropDownFacilityID ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["111"]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:50]]></Time>
<TimeTick>1523963030</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="148" Source="WebStrat_Automation" SourceLine="91" >
<Disp><![CDATA[[ DropDownFacilityID ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownPayerID ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04301392"]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:51]]></Time>
<TimeTick>1523963031</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="151" Source="WebStrat_Automation" SourceLine="93" >
<Disp><![CDATA[[ txtDropDownPayerID ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPtIDMedRec ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["WS.AC.18Q2R1.2.0"]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:52]]></Time>
<TimeTick>1523963032</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="154" Source="WebStrat_Automation" SourceLine="95" >
<Disp><![CDATA[[ TextBoxPtIDMedRec ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ TextBoxAdmitDate ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/1/2018"]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:53]]></Time>
<TimeTick>1523963033</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="157" Source="WebStrat_Automation" SourceLine="97" >
<Disp><![CDATA[[ TextBoxAdmitDate ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ TextBoxDischDate ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/1/2018"]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:54]]></Time>
<TimeTick>1523963034</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="160" Source="WebStrat_Automation" SourceLine="98" >
<Disp><![CDATA[[ TextBoxDischDate ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ TextBoxSex ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["M"]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:55]]></Time>
<TimeTick>1523963035</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="163" Source="WebStrat_Automation" SourceLine="101" >
<Disp><![CDATA[[ TextBoxSex ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ TextBoxBirth ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["01/01/1977"]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:55]]></Time>
<TimeTick>1523963035</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="166" Source="WebStrat_Automation" SourceLine="103" >
<Disp><![CDATA[[ TextBoxBirth ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ txtDropDownDStat ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["01"]]></Details>
<Time><![CDATA[4/17/2018 - 16:33:56]]></Time>
<TimeTick>1523963036</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="169" Source="WebStrat_Automation" SourceLine="105" >
<Disp><![CDATA[[ txtDropDownDStat ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "[ WebEdit ]" (of class WebEdit).
Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:14]]></Time>
<TimeTick>1523963174</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Type = text<br>Name = WebEdit<br>Mercury Class = WebEdit<br>htmltag = INPUT<br>Html Id = TextBoxBillType<br>Height = 22<br>]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:14]]></Time>
<TimeTick>1523963174</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="181" status="Warning" nType="Description" Source="WebStrat_Automation" SourceLine="107" >
<Disp><![CDATA[[ WebEdit ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="180" status="Failed" nType="Run Error" Source="WebStrat_Automation" SourceLine="107" >
<Disp><![CDATA[[ WebEdit ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ TextBoxCoder ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["18Q2R1"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:35]]></Time>
<TimeTick>1523963195</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="184" Source="WebStrat_Automation" SourceLine="110" >
<Disp><![CDATA[[ TextBoxCoder ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Summary"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:41]]></Time>
<TimeTick>1523963201</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="187" Source="WebStrat_Automation" SourceLine="116" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:42]]></Time>
<TimeTick>1523963202</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="190" Source="WebStrat_Automation" SourceLine="117" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ dx0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["B699"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:47]]></Time>
<TimeTick>1523963207</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="194" Source="WebStrat_Automation" SourceLine="145" >
<Disp><![CDATA[[ dx0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Onset0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:47]]></Time>
<TimeTick>1523963207</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="197" Source="WebStrat_Automation" SourceLine="146" >
<Disp><![CDATA[[ Onset0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ rev0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0100"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:48]]></Time>
<TimeTick>1523963208</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="200" Source="WebStrat_Automation" SourceLine="149" >
<Disp><![CDATA[[ rev0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ hcpcs0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["C9462"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:48]]></Time>
<TimeTick>1523963208</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="203" Source="WebStrat_Automation" SourceLine="151" >
<Disp><![CDATA[[ hcpcs0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ Units0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:48]]></Time>
<TimeTick>1523963208</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="206" Source="WebStrat_Automation" SourceLine="154" >
<Disp><![CDATA[[ Units0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ date0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["04/01/2018"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:49]]></Time>
<TimeTick>1523963209</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="209" Source="WebStrat_Automation" SourceLine="156" >
<Disp><![CDATA[[ date0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ charges0 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["500"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:49]]></Time>
<TimeTick>1523963209</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="212" Source="WebStrat_Automation" SourceLine="158" >
<Disp><![CDATA[[ charges0 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ rev1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:49]]></Time>
<TimeTick>1523963209</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="215" Source="WebStrat_Automation" SourceLine="161" >
<Disp><![CDATA[[ rev1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ hcpcs1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["10060"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:50]]></Time>
<TimeTick>1523963210</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="218" Source="WebStrat_Automation" SourceLine="163" >
<Disp><![CDATA[[ hcpcs1 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ Units1 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/17/2018 - 16:36:50]]></Time>
<TimeTick>1523963210</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="221" Source="WebStrat_Automation" SourceLine="166" >