<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.51" os="Windows 7" host="LH7U05CG5443KYD"><DocLocation><![CDATA[C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStrat_Search_Functionality]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[WebStrat_Search_Functionality]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="0" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[WebStrat_Automation]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[3/1/2018 - 21:20:45]]></Time>
<TimeTick>1519919445</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[3/1/2018 - 21:20:45]]></Time>
<TimeTick>1519919445</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="10" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="3" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[[ TextBoxUserId ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ERC_WSD"]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:00]]></Time>
<TimeTick>1519919460</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="13" >
<Disp><![CDATA[[ TextBoxUserId ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPassword ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hss_PATDB"]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:00]]></Time>
<TimeTick>1519919460</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="16" >
<Disp><![CDATA[[ TextBoxPassword ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Login ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:00]]></Time>
<TimeTick>1519919460</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="19" >
<Disp><![CDATA[[ Login ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Page ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:10]]></Time>
<TimeTick>1519919470</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" >
<Disp><![CDATA[[ Page ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:30]]></Time>
<TimeTick>1519919490</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:30]]></Time>
<TimeTick>1519919490</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="53" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:30]]></Time>
<TimeTick>1519919490</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Dummy"]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:31]]></Time>
<TimeTick>1519919491</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="59" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:31]]></Time>
<TimeTick>1519919491</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="62" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:54]]></Time>
<TimeTick>1519919514</TimeTick>
<NodeArgs eType="General" icon="9" nRep="68" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:55]]></Time>
<TimeTick>1519919515</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="71" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:56]]></Time>
<TimeTick>1519919516</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="74" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:21:56]]></Time>
<TimeTick>1519919516</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="75" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[3/1/2018 - 21:22:35]]></Time>
<TimeTick>1519919555</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="83" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:22:39]]></Time>
<TimeTick>1519919559</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="86" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:22:40]]></Time>
<TimeTick>1519919560</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="89" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[3/1/2018 - 21:23:45]]></Time>
<TimeTick>1519919625</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="92" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:24:14]]></Time>
<TimeTick>1519919654</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="95" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:24:15]]></Time>
<TimeTick>1519919655</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="98" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[3/1/2018 - 21:24:16]]></Time>
<TimeTick>1519919656</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="101" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ASC_Claim_Validation"]]></Details>
<Time><![CDATA[3/1/2018 - 21:24:22]]></Time>
<TimeTick>1519919662</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="104" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:24:22]]></Time>
<TimeTick>1519919662</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="107" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[3/1/2018 - 21:24:24]]></Time>
<TimeTick>1519919664</TimeTick>
<NodeArgs eType="General" icon="9" nRep="110" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[3/1/2018 - 21:24:24]]></Time>
<TimeTick>1519919664</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="113" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[3/1/2018 - 21:24:24]]></Time>
<TimeTick>1519919664</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="116" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:24:24]]></Time>
<TimeTick>1519919664</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="117" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[3/1/2018 - 21:26:17]]></Time>
<TimeTick>1519919777</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="125" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:26:42]]></Time>
<TimeTick>1519919802</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="128" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:27:03]]></Time>
<TimeTick>1519919823</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="131" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[3/1/2018 - 21:27:40]]></Time>
<TimeTick>1519919860</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="134" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:28:01]]></Time>
<TimeTick>1519919881</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="137" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 21:28:07]]></Time>
<TimeTick>1519919887</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="141" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[3/1/2018 - 21:28:10]]></Time>
<TimeTick>1519919890</TimeTick>
<NodeArgs eType="General" icon="0" nRep="143" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="3/1/2018 - 21:20:40" eTime="3/1/2018 - 21:28:10" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="6" status="Passed" >
<Disp><![CDATA[WebStrat_Automation Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="3/1/2018 - 21:20:39" eTime="3/1/2018 - 21:28:10" passed="1" failed="0" warnings="0" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test WebStrat_Search_Functionality Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>