<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.51" os="Windows 7" host="LH7U05CG5443KYD"><DocLocation><![CDATA[C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\GUITest2]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[GUITest2]]></DName>
<Res><![CDATA[Res32]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="0" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[2/21/2018 - 19:55:48]]></Time>
<TimeTick>1519223148</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[2/21/2018 - 19:55:48]]></Time>
<TimeTick>1519223148</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ TextBoxUserId ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ERC_WSD"]]></Details>
<Time><![CDATA[2/21/2018 - 19:55:58]]></Time>
<TimeTick>1519223158</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="14" Source="Action1" SourceLine="14" >
<Disp><![CDATA[[ TextBoxUserId ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPassword ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hss_PATDB"]]></Details>
<Time><![CDATA[2/21/2018 - 19:55:58]]></Time>
<TimeTick>1519223158</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="17" Source="Action1" SourceLine="17" >
<Disp><![CDATA[[ TextBoxPassword ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Login ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:55:58]]></Time>
<TimeTick>1519223158</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ Login ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[2/21/2018 - 19:56:10]]></Time>
<TimeTick>1519223170</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" Source="Action1" SourceLine="21" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[2/21/2018 - 19:56:25]]></Time>
<TimeTick>1519223185</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:56:25]]></Time>
<TimeTick>1519223185</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" Source="Action1" SourceLine="41" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[2/21/2018 - 19:56:26]]></Time>
<TimeTick>1519223186</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Action1" SourceLine="44" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ASC_Claim_Validation"]]></Details>
<Time><![CDATA[2/21/2018 - 19:56:30]]></Time>
<TimeTick>1519223190</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="34" Source="Action1" SourceLine="73" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:56:30]]></Time>
<TimeTick>1519223190</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="37" Source="Action1" SourceLine="74" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2/21/2018 - 19:56:32]]></Time>
<TimeTick>1519223192</TimeTick>
<NodeArgs eType="General" icon="10" nRep="40" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[2/21/2018 - 19:56:32]]></Time>
<TimeTick>1519223192</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="43" Source="Action1" SourceLine="81" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:56:32]]></Time>
<TimeTick>1519223192</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="44" Source="Action1" SourceLine="84" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:04]]></Time>
<TimeTick>1519223224</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="50" Source="Action1" SourceLine="106" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:04]]></Time>
<TimeTick>1519223224</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="53" Source="Action1" SourceLine="109" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:16]]></Time>
<TimeTick>1519223236</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" Source="Action1" SourceLine="115" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:16]]></Time>
<TimeTick>1519223236</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="59" Source="Action1" SourceLine="116" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Web.Strat]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:18]]></Time>
<TimeTick>1519223238</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["Web.Strat"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (2 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (2 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Web.Strat<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>title=Web.Strat - Internet Explorer<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openurl=http://webstratstg/HSS/WebStrat/login.aspx<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>opentitle=Web.Strat Login<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:18]]></Time>
<TimeTick>1519223238</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="62" Source="Action1" SourceLine="119" >
<Disp><![CDATA["Web.Strat"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Web.Strat]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:18]]></Time>
<TimeTick>1519223238</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[IFrameSearch]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:18]]></Time>
<TimeTick>1519223238</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:18]]></Time>
<TimeTick>1519223238</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="66" Source="Action1" SourceLine="119" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:19]]></Time>
<TimeTick>1519223239</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" Source="Action1" SourceLine="121" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["apc_paystat_s"]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:34]]></Time>
<TimeTick>1519223254</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="72" Source="Action1" SourceLine="73" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:34]]></Time>
<TimeTick>1519223254</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="75" Source="Action1" SourceLine="74" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:36]]></Time>
<TimeTick>1519223256</TimeTick>
<NodeArgs eType="General" icon="10" nRep="78" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:36]]></Time>
<TimeTick>1519223256</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="81" Source="Action1" SourceLine="81" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:57:36]]></Time>
<TimeTick>1519223256</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="82" Source="Action1" SourceLine="84" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:58:13]]></Time>
<TimeTick>1519223293</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="88" Source="Action1" SourceLine="106" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:58:14]]></Time>
<TimeTick>1519223294</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="91" Source="Action1" SourceLine="109" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[2/21/2018 - 19:58:52]]></Time>
<TimeTick>1519223332</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="94" Source="Action1" SourceLine="115" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:14]]></Time>
<TimeTick>1519223354</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="97" Source="Action1" SourceLine="116" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:16]]></Time>
<TimeTick>1519223356</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="100" Source="Action1" SourceLine="119" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:17]]></Time>
<TimeTick>1519223357</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="103" Source="Action1" SourceLine="121" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["WS.ASC.17Q3R2.1.0"]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:32]]></Time>
<TimeTick>1519223372</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="106" Source="Action1" SourceLine="73" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:32]]></Time>
<TimeTick>1519223372</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="109" Source="Action1" SourceLine="74" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:34]]></Time>
<TimeTick>1519223374</TimeTick>
<NodeArgs eType="General" icon="10" nRep="112" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:34]]></Time>
<TimeTick>1519223374</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="115" Source="Action1" SourceLine="81" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:34]]></Time>
<TimeTick>1519223374</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="116" Source="Action1" SourceLine="84" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:48]]></Time>
<TimeTick>1519223388</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="122" Source="Action1" SourceLine="106" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:48]]></Time>
<TimeTick>1519223388</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="125" Source="Action1" SourceLine="109" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:59]]></Time>
<TimeTick>1519223399</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="128" Source="Action1" SourceLine="115" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 19:59:59]]></Time>
<TimeTick>1519223399</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="131" Source="Action1" SourceLine="116" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:00:02]]></Time>
<TimeTick>1519223402</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="134" Source="Action1" SourceLine="119" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[2/21/2018 - 20:00:02]]></Time>
<TimeTick>1519223402</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="137" Source="Action1" SourceLine="121" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["EXTFee_AT"]]></Details>
<Time><![CDATA[2/21/2018 - 20:00:17]]></Time>
<TimeTick>1519223417</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="140" Source="Action1" SourceLine="73" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:00:17]]></Time>
<TimeTick>1519223417</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="143" Source="Action1" SourceLine="74" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2/21/2018 - 20:00:19]]></Time>
<TimeTick>1519223419</TimeTick>
<NodeArgs eType="General" icon="10" nRep="146" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[2/21/2018 - 20:00:20]]></Time>
<TimeTick>1519223420</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="149" Source="Action1" SourceLine="81" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:00:20]]></Time>
<TimeTick>1519223420</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="150" Source="Action1" SourceLine="84" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:00:48]]></Time>
<TimeTick>1519223448</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="156" Source="Action1" SourceLine="106" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:00:49]]></Time>
<TimeTick>1519223449</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="159" Source="Action1" SourceLine="109" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[2/21/2018 - 20:01:28]]></Time>
<TimeTick>1519223488</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="162" Source="Action1" SourceLine="115" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:01:51]]></Time>
<TimeTick>1519223511</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="165" Source="Action1" SourceLine="116" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:01:53]]></Time>
<TimeTick>1519223513</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="168" Source="Action1" SourceLine="119" >
<Disp><![CDATA[Clear.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[2/21/2018 - 20:01:54]]></Time>
<TimeTick>1519223514</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="171" Source="Action1" SourceLine="121" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["WS.V1801.ONMPRF.1.0"]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:09]]></Time>
<TimeTick>1519223529</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="174" Source="Action1" SourceLine="73" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:09]]></Time>
<TimeTick>1519223529</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="177" Source="Action1" SourceLine="74" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:11]]></Time>
<TimeTick>1519223531</TimeTick>
<NodeArgs eType="General" icon="10" nRep="180" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:11]]></Time>
<TimeTick>1519223531</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="183" Source="Action1" SourceLine="81" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:11]]></Time>
<TimeTick>1519223531</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="184" Source="Action1" SourceLine="84" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:45]]></Time>
<TimeTick>1519223565</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="190" Source="Action1" SourceLine="106" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:45]]></Time>
<TimeTick>1519223565</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="193" Source="Action1" SourceLine="109" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:57]]></Time>
<TimeTick>1519223577</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="196" Source="Action1" SourceLine="115" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:57]]></Time>
<TimeTick>1519223577</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="199" Source="Action1" SourceLine="116" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Clear.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[2/21/2018 - 20:02:59]]></Time>
<TimeTick>1519223579</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="202" Source="Action1" SourceLine="119" >