<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.51" os="Windows 7" host="LH7U05CG5443KYD"><DocLocation><![CDATA[C:\Proj_WebStrat_UFT_Automation\FunctionalLibrary\WebStrat_Search_Functionality]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[WebStrat_Search_Functionality]]></DName>
<Res><![CDATA[Res195]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="0" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[WebStrat_Automation]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:04]]></Time>
<TimeTick>1519905724</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",1]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:04]]></Time>
<TimeTick>1519905724</TimeTick>
<NodeArgs eType="Replay" icon="3" nRep="10" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="3" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[[ TextBoxUserId ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ERC_WSD"]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:16]]></Time>
<TimeTick>1519905736</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="13" >
<Disp><![CDATA[[ TextBoxUserId ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ TextBoxPassword ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hss_PATDB"]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:16]]></Time>
<TimeTick>1519905736</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="16" >
<Disp><![CDATA[[ TextBoxPassword ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Login ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:16]]></Time>
<TimeTick>1519905736</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="19" >
<Disp><![CDATA[[ Login ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Page ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:26]]></Time>
<TimeTick>1519905746</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" >
<Disp><![CDATA[[ Page ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:28]]></Time>
<TimeTick>1519905748</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:29]]></Time>
<TimeTick>1519905749</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:30]]></Time>
<TimeTick>1519905750</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="35" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Dummy"]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:31]]></Time>
<TimeTick>1519905751</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="38" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:31]]></Time>
<TimeTick>1519905751</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="41" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:52]]></Time>
<TimeTick>1519905772</TimeTick>
<NodeArgs eType="General" icon="9" nRep="44" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:53]]></Time>
<TimeTick>1519905773</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:54]]></Time>
<TimeTick>1519905774</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="50" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:55]]></Time>
<TimeTick>1519905775</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="53" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:32:55]]></Time>
<TimeTick>1519905775</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[3/1/2018 - 17:33:27]]></Time>
<TimeTick>1519905807</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="62" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:33:31]]></Time>
<TimeTick>1519905811</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="65" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:33:32]]></Time>
<TimeTick>1519905812</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="68" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[3/1/2018 - 17:34:26]]></Time>
<TimeTick>1519905866</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="71" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:34:54]]></Time>
<TimeTick>1519905894</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="74" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:34:55]]></Time>
<TimeTick>1519905895</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="77" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[3/1/2018 - 17:34:56]]></Time>
<TimeTick>1519905896</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="80" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ASC_Claim_Validation"]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:01]]></Time>
<TimeTick>1519905901</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="83" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:01]]></Time>
<TimeTick>1519905901</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="86" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:03]]></Time>
<TimeTick>1519905903</TimeTick>
<NodeArgs eType="General" icon="9" nRep="89" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:03]]></Time>
<TimeTick>1519905903</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="92" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:03]]></Time>
<TimeTick>1519905903</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="95" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:03]]></Time>
<TimeTick>1519905903</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="96" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:14]]></Time>
<TimeTick>1519905914</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="104" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:18]]></Time>
<TimeTick>1519905918</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="107" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:18]]></Time>
<TimeTick>1519905918</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="110" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:35]]></Time>
<TimeTick>1519905935</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="113" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:35]]></Time>
<TimeTick>1519905935</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="116" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:37]]></Time>
<TimeTick>1519905937</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="119" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:37]]></Time>
<TimeTick>1519905937</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="122" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["apc_paystat_s"]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:43]]></Time>
<TimeTick>1519905943</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="125" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:43]]></Time>
<TimeTick>1519905943</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="128" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:45]]></Time>
<TimeTick>1519905945</TimeTick>
<NodeArgs eType="General" icon="9" nRep="131" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:45]]></Time>
<TimeTick>1519905945</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="134" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:45]]></Time>
<TimeTick>1519905945</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="137" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:35:45]]></Time>
<TimeTick>1519905945</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="138" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[3/1/2018 - 17:36:16]]></Time>
<TimeTick>1519905976</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="146" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:36:20]]></Time>
<TimeTick>1519905980</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="149" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:36:21]]></Time>
<TimeTick>1519905981</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="152" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:21]]></Time>
<TimeTick>1519906041</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="155" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:49]]></Time>
<TimeTick>1519906069</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="158" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:50]]></Time>
<TimeTick>1519906070</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="161" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:51]]></Time>
<TimeTick>1519906071</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="164" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["hopd_paystat_t"]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:56]]></Time>
<TimeTick>1519906076</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="167" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:56]]></Time>
<TimeTick>1519906076</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="170" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:58]]></Time>
<TimeTick>1519906078</TimeTick>
<NodeArgs eType="General" icon="9" nRep="173" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:58]]></Time>
<TimeTick>1519906078</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="176" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:58]]></Time>
<TimeTick>1519906078</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="179" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:37:58]]></Time>
<TimeTick>1519906078</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="180" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:09]]></Time>
<TimeTick>1519906089</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="188" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:13]]></Time>
<TimeTick>1519906093</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="191" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:14]]></Time>
<TimeTick>1519906094</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="194" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:30]]></Time>
<TimeTick>1519906110</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="197" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:30]]></Time>
<TimeTick>1519906110</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="200" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:32]]></Time>
<TimeTick>1519906112</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="203" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:32]]></Time>
<TimeTick>1519906112</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="206" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ tb_medrecnum ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["EXTFee_AT"]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:38]]></Time>
<TimeTick>1519906118</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="209" >
<Disp><![CDATA[[ tb_medrecnum ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ Search ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:38]]></Time>
<TimeTick>1519906118</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="212" >
<Disp><![CDATA[[ Search ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA["[ dg_search ]":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:39]]></Time>
<TimeTick>1519906119</TimeTick>
<NodeArgs eType="General" icon="9" nRep="215" >
<Disp><![CDATA["[ dg_search ]":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[2, 9]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:40]]></Time>
<TimeTick>1519906120</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="218" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ dg_search ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[7]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:40]]></Time>
<TimeTick>1519906120</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="221" >
<Disp><![CDATA[[ dg_search ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ WbfGrid ].Object]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:38:40]]></Time>
<TimeTick>1519906120</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="222" >
<Disp><![CDATA[[ WbfGrid ].Object]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ Table1 ].GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 8]]></Details>
<Time><![CDATA[3/1/2018 - 17:39:13]]></Time>
<TimeTick>1519906153</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="230" >
<Disp><![CDATA[[ Table1 ].GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ File ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:39:17]]></Time>
<TimeTick>1519906157</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="233" >
<Disp><![CDATA[[ File ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ Save (Ctrl+S) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:39:19]]></Time>
<TimeTick>1519906159</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="236" >
<Disp><![CDATA[[ Save (Ctrl+S) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Search"]]></Details>
<Time><![CDATA[3/1/2018 - 17:40:17]]></Time>
<TimeTick>1519906217</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="239" >
<Disp><![CDATA[[ TabStrip1 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[[ TabStrip1 ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:40:45]]></Time>
<TimeTick>1519906245</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="242" >
<Disp><![CDATA[[ TabStrip1 ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[[ Clear ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[3/1/2018 - 17:40:47]]></Time>
<TimeTick>1519906247</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="245" >
<Disp><![CDATA[[ Clear ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[[ ddl_fld ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Medical Record Number"]]></Details>
<Time><![CDATA[3/1/2018 - 17:40:47]]></Time>
<TimeTick>1519906247</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="248" >
<Disp><![CDATA[[ ddl_fld ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79">